# .github/workflows/build.yml
name: Build and Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Cache apt packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: >-
            pkg-config
            libwayland-client0
            libwayland-cursor0
            libwayland-egl1
            libwayland-server0
            libqt6waylandclient6
            libqt6waylandegl6
            qtwayland6
            libgl1-mesa-dri
            libglx-mesa0
            libsystemd-dev
            python3-dev
          version: 1.0

      - name: Set Environment Variables
        run: |
          echo "QT_QPA_PLATFORM=wayland" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:/lib/x86_64-linux-gnu/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel setuptools
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Create env file
        run: |
          echo "GITHUB_ACCESS_TOKEN=${{ secrets.GIT_API_KEY }}" > .env

      - name: Build with PyInstaller
        run: |
          pyinstaller main.spec --clean
          cd dist
          # Zip single executable file directly
          zip GitUpdater-${{ github.ref_name }}-linux.zip GitUpdater

      - name: Create Release
        uses: softprops/action-gh-release@v2.1.0
        with:
          files: dist/GitUpdater-${{ github.ref_name }}-linux.zip
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: GitUpdater-${{ github.ref_name }}-linux
          path: dist/GitUpdater # Point directly to executable
          retention-days: 7
